entity: ludekcizinsky
project: pbr-generation

use_pretrained_unet: false # true if you want to run non finetuned model
run_name: twilight-sponge-160
run_id: fstkreeo
num_workers: 10
val_debug_size: -1


hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False