seed: 42
debug: false
output_dir: outputs
checkpoint_dir: /scratch/izar/cizinsky/garment-completion/checkpoints
max_train_samples: 1792000 # 28000*64

logger:
  project: pbr-generation
  tags: [baseline]
  run_id: null # tqtzd06l

data:
  val_size: 300
  val_sel_texture_names: [
    "Denim_Magenta_Floral_Print",
    "Herringbone_Lime_Green_Animal_Print_(Leopard)",
    "Georgette_Emerald_Green_Checks",
    "Lace_Pumpkin_Orange_Brocade",
    "Jacquard_Magenta_Animal_Print_(Leopard)"
  ]
  pbr_maps_path: "/scratch/izar/cizinsky/garment-completion/pbr_maps/dresscode"
  mask_path: "/scratch/izar/cizinsky/garment-completion/masks/shirt.png"
  num_workers: 20
  batch_size: 20 # baseline: 64
  res: 512 # baseline: 512

# Optimisation
optim:
  lr: 1e-5
  weight_decay: 1e-2
  warmup_steps: 1000

  # Scheduler - reduce on plateau
  plateau_patience: 10 # how many val/f1 to wait before reducing
  plateau_factor: 0.5 # reduce by this factor
  min_lr: 1e-6  # minimum learning rate
  plateau_mode: "min" # mode for plateau scheduler
  plateau_metric: "val/loss" # metric to monitor for plateau scheduler

  # Gradient clipping
  max_grad_norm: 1.0 # gradient clipping
  grad_norm_type: 2.0 # norm type for gradient clipping

model:
  vae_path: "/home/cizinsky/garment-texture-completion/data_generation/dresscode/material_gen"
  diffusion_path: "stable-diffusion-v1-5/stable-diffusion-v1-5"
  conditioning_dropout_prob: 0.05 # classifier-free guidance / baseline: 0.05
  ddim_loss: true # baseline: true

trainer:
  max_steps: -1 #  will be computed during runtime as max_train_samples // batch_size / baseline: 28000 (with batch size 8)
  accelerator: gpu
  devices: 1
  checkpoints_total_limit: 2
  checkpoint_every_n_train_steps: 5000 # baseline: 4000
  val_check_interval: 1000 # in steps / baseline: one per epoch
  precision: 16-mixed
  log_every_n_steps: 10 # baseline: 1


hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}_${now:%H-%M-%S}
  job:
    chdir: False