seed: 42

logger:
  project: pbr-generation
  tags: [dev]

data:
  trn_frac: 0.9
  pbr_maps_path: "/scratch/izar/cizinsky/garment-completion/pbr_maps/dresscode"
  mask_path: "/scratch/izar/cizinsky/garment-completion/masks/shirt.png"
  batch_size: 8
  num_workers: 2

model:
  learning_rate: 5e-5
  weight_decay: 1e-2
  vae_path: "/home/cizinsky/garment-texture-completion/src/data_generation/dresscode/material_gen"
  diffusion_path: "stable-diffusion-v1-5/stable-diffusion-v1-5"
  conditioning_dropout_prob: 0.05 # classifier-free guidance
  ddim_loss: true


# todo: gradient checkpointing
trainer:
  max_steps: 28000
  accelerator: gpu
  devices: 1
  checkpoint_every_n_epochs: 4000
  checkpoints_total_limit: 5
  accumulate_grad_batches: 1 
  max_grad_norm: 1 

######################################


hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: False