seed: 42
debug: false
output_dir: outputs
checkpoint_dir: /scratch/izar/cizinsky/garment-completion/checkpoints
max_train_samples: 1792000
logger:
  project: pbr-generation
  tags:
  - ddim
  run_id: null
data:
  val_size: 300
  val_sel_texture_names:
  - Denim_Magenta_Floral_Print
  - Herringbone_Lime_Green_Animal_Print_(Leopard)
  - Georgette_Emerald_Green_Checks
  - Lace_Pumpkin_Orange_Brocade
  - Jacquard_Magenta_Animal_Print_(Leopard)
  pbr_maps_path: /scratch/izar/cizinsky/garment-completion/pbr_maps/dresscode
  mask_path: /scratch/izar/cizinsky/garment-completion/masks/shirt.png
  num_workers: 20
  batch_size: 20
  res: 512
optim:
  lr: 1.0e-05
  weight_decay: 0.01
  warmup_steps: 1000
  plateau_patience: 7
  plateau_factor: 0.5
  min_lr: 1.0e-06
  plateau_mode: min
  plateau_metric: val/lpips
  max_grad_norm: 1.0
  grad_norm_type: 2.0
  ddim_loss: true
  ddim_loss_weight: 0.0
model:
  vae_path: /home/cizinsky/garment-texture-completion/data_generation/dresscode/material_gen
  diffusion_path: stable-diffusion-v1-5/stable-diffusion-v1-5
  conditioning_dropout_prob: 0.05
trainer:
  max_steps: 89600
  accelerator: gpu
  devices: 1
  checkpoints_total_limit: 2
  checkpoint_every_n_train_steps: 5000
  val_check_interval: 1000
  precision: 16-mixed
  log_every_n_steps: 10
